spring:
  config:
    import: file:.env[.properties]
  application:
    name: Bank-Application
  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
